### ISSUE TITLE
(Posted on boiii GitHub as well) Easy download of custom maps for dedicated servers

### ISSUE THREAD

**Issue by SpartanBart** [Dss0/t7-server-config#18]
(I posted this in the boiii GitHub page but I thought it would be good to put it here as well, If this shouldn't be here please remove.) I would like to propose a feature I know it would be hard to develop and implement, but a dedicated tool to download mods/custom maps for dedicated servers on VPS/dedicated Servers. You can use SteamCMD to download maps from the workshop but 90% of the time downloads of custom maps timeout when using SteamCMD, I presume because of the size of the maps. This would be a good application and tool that is packed in with the server files.

**Comment by Dss0** [comment]
this has nothing to do with the server configs. just transfer the map files from your pc to your vps, the server only needs zm_mapname and en_zm_mapname.ff anyways, you can skip all the xpaks and sound files.
