### ISSUE TITLE
incorrect documentation in T7x_ZM_Server.bat for mods

### ISSUE THREAD

**Issue by danielle-esposito** [Dss0/t7-server-config#22]
The documentation in these files says:

`Load a mod on your server
Example: ModfolderName=mods/bots`

however, this will not work to load a mod. if you follow this it results in the following error.
`Command line: -dedicated +set fs_game "mods/zm_judge_noshield" +set net_port "27069"  +set logfile 2 +exec server_zm.cfg
Mod folder has an invalid character: mods\zm_judge_noshield. The folder must be a single folder name.`

 it needs the steam workshop id of the mod (no "mods/bots"). 

`Load a mod on your server
Example: ModfolderName=*steamworkshopid*`

**Comment by Dss0** [comment]
Fixed in [5b8949b](https://github.com/Dss0/t7-server-config/commit/5b8949b6e1ee401f7343616354fd59fb33d99f0e)
